[package]
name = "cosmicrafts_icp_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.12.1"
ic-cdk-macros = "0.8.4"
serde = { version = "1.0.196", features = ["derive"] }
candid = "0.10.3"