[package]
name = "cosmicrafts_icp_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.12.0"
ic-cdk-macros = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
candid = "0.10.1"
