[package]
name = "cosmicrafts_icp_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7.1"
serde = { version = "1.0.176", features = ["derive"] }
candid = "0.9.3"
serde_cbor = "0.11.2"
ic-websocket-cdk = "0.3.2"
